include ../../../../projects/linux/_mk-generic.inc
include ../../../_libs-config.inc

include _module-app-throughput.inc

dumpinfo:
	@echo 'CC' $(CC)
	@echo ''
	@echo 'CXX' $(CXX)
	@echo ''
	@echo 'CC_MISC' $(CC_MISC)
	@echo 'CC_NATIVE' $(CC_NATIVE)
	@echo ''
	@echo 'DEFINES' $(DEFINES)
	@echo ''
	@echo 'INCLUDES' $(INCLUDES)
	@echo ''
	
